[project]
name = "ryutai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.0",
    "numba",
    "dearpygui>=2.0.0",
    "pyvista[all]>=0.43.0",
    "pyinstaller>=6.0.0",
]
